// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: dhukuti/oms/v1/oms.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Side is the direction of an order. The unspecified zero value is invalid
// rather than defaulting, so a caller that forgets the field is rejected
// instead of silently having its order treated as a buy.
type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_BUY":         1,
		"SIDE_SELL":        2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_dhukuti_oms_v1_oms_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_dhukuti_oms_v1_oms_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{0}
}

// OrderType is LIMIT or MARKET. Unspecified is invalid, same reasoning as Side.
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
	OrderType_ORDER_TYPE_MARKET      OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_LIMIT",
		2: "ORDER_TYPE_MARKET",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_LIMIT":       1,
		"ORDER_TYPE_MARKET":      2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_dhukuti_oms_v1_oms_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_dhukuti_oms_v1_oms_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{1}
}

type PlaceOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// symbol is the instrument, e.g. "NABIL". Uppercase A-Z0-9, max 12 chars.
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// account_id is the account the order is placed for. Authenticating that
	// the caller is entitled to act for this account is out of scope for v1
	// (see ADR-005) — the field is trusted as sent.
	AccountId string    `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Side      Side      `protobuf:"varint,3,opt,name=side,proto3,enum=dhukuti.oms.v1.Side" json:"side,omitempty"`
	Type      OrderType `protobuf:"varint,4,opt,name=type,proto3,enum=dhukuti.oms.v1.OrderType" json:"type,omitempty"`
	// price is in ticks and is ignored for MARKET orders.
	Price         int64 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64 `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PlaceOrderRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *PlaceOrderRequest) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PlaceOrderRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type PlaceOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order_id is assigned by the venue, not the client. A client-supplied ID
	// would let one client claim another's identifier and then cancel its
	// orders.
	OrderId int64 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// log_position is the order's write-ahead log position, durable before any
	// matching happened. It is not an order ID — cancels get positions too.
	LogPosition int64 `protobuf:"varint,2,opt,name=log_position,json=logPosition,proto3" json:"log_position,omitempty"`
	// trades is every execution this order caused, in match order. Empty means
	// the order rested without crossing anything.
	Trades []*Trade `protobuf:"bytes,3,rep,name=trades,proto3" json:"trades,omitempty"`
	// resting_quantity is what remains in the book. A MARKET order's unfilled
	// remainder is dropped rather than rested, so this is always 0 for MARKET.
	RestingQuantity int64 `protobuf:"varint,4,opt,name=resting_quantity,json=restingQuantity,proto3" json:"resting_quantity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceOrderResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PlaceOrderResponse) GetLogPosition() int64 {
	if x != nil {
		return x.LogPosition
	}
	return 0
}

func (x *PlaceOrderResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

func (x *PlaceOrderResponse) GetRestingQuantity() int64 {
	if x != nil {
		return x.RestingQuantity
	}
	return 0
}

type CancelOrderRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Symbol  string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// account_id must match the account that placed the order. Same v1 caveat
	// as PlaceOrderRequest.account_id: the claim is checked but not
	// authenticated.
	AccountId     string `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{2}
}

func (x *CancelOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CancelOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CancelOrderRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogPosition   int64                  `protobuf:"varint,1,opt,name=log_position,json=logPosition,proto3" json:"log_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderResponse) GetLogPosition() int64 {
	if x != nil {
		return x.LogPosition
	}
	return 0
}

type StreamTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTradesRequest) Reset() {
	*x = StreamTradesRequest{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTradesRequest) ProtoMessage() {}

func (x *StreamTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTradesRequest.ProtoReflect.Descriptor instead.
func (*StreamTradesRequest) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{4}
}

func (x *StreamTradesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type Trade struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// trade_id is unique within a symbol.
	TradeId int64  `protobuf:"varint,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	Symbol  string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// price is always the resting (maker) order's price, never the incoming
	// taker's — the taker crossed a price that was already on offer.
	Price          int64  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity       int64  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	MakerOrderId   int64  `protobuf:"varint,5,opt,name=maker_order_id,json=makerOrderId,proto3" json:"maker_order_id,omitempty"`
	TakerOrderId   int64  `protobuf:"varint,6,opt,name=taker_order_id,json=takerOrderId,proto3" json:"taker_order_id,omitempty"`
	MakerAccountId string `protobuf:"bytes,7,opt,name=maker_account_id,json=makerAccountId,proto3" json:"maker_account_id,omitempty"`
	TakerAccountId string `protobuf:"bytes,8,opt,name=taker_account_id,json=takerAccountId,proto3" json:"taker_account_id,omitempty"`
	// executed_at is a metric, not an ordering key. Matching order is
	// determined by log position, and replay does not reproduce this field —
	// see ADR-003.
	ExecutedAtUnixNano int64 `protobuf:"varint,9,opt,name=executed_at_unix_nano,json=executedAtUnixNano,proto3" json:"executed_at_unix_nano,omitempty"`
	// taker_side is the incoming order's direction, which is what says who
	// bought: on SIDE_BUY the taker pays cash and receives shares. Without it a
	// trade names both parties but not which way value moved.
	TakerSide     Side `protobuf:"varint,10,opt,name=taker_side,json=takerSide,proto3,enum=dhukuti.oms.v1.Side" json:"taker_side,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{5}
}

func (x *Trade) GetTradeId() int64 {
	if x != nil {
		return x.TradeId
	}
	return 0
}

func (x *Trade) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Trade) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetMakerOrderId() int64 {
	if x != nil {
		return x.MakerOrderId
	}
	return 0
}

func (x *Trade) GetTakerOrderId() int64 {
	if x != nil {
		return x.TakerOrderId
	}
	return 0
}

func (x *Trade) GetMakerAccountId() string {
	if x != nil {
		return x.MakerAccountId
	}
	return ""
}

func (x *Trade) GetTakerAccountId() string {
	if x != nil {
		return x.TakerAccountId
	}
	return ""
}

func (x *Trade) GetExecutedAtUnixNano() int64 {
	if x != nil {
		return x.ExecutedAtUnixNano
	}
	return 0
}

func (x *Trade) GetTakerSide() Side {
	if x != nil {
		return x.TakerSide
	}
	return Side_SIDE_UNSPECIFIED
}

var File_dhukuti_oms_v1_oms_proto protoreflect.FileDescriptor

const file_dhukuti_oms_v1_oms_proto_rawDesc = "" +
	"\n" +
	"\x18dhukuti/oms/v1/oms.proto\x12\x0edhukuti.oms.v1\"\xd5\x01\n" +
	"\x11PlaceOrderRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12(\n" +
	"\x04side\x18\x03 \x01(\x0e2\x14.dhukuti.oms.v1.SideR\x04side\x12-\n" +
	"\x04type\x18\x04 \x01(\x0e2\x19.dhukuti.oms.v1.OrderTypeR\x04type\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x03R\bquantity\"\xac\x01\n" +
	"\x12PlaceOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12!\n" +
	"\flog_position\x18\x02 \x01(\x03R\vlogPosition\x12-\n" +
	"\x06trades\x18\x03 \x03(\v2\x15.dhukuti.oms.v1.TradeR\x06trades\x12)\n" +
	"\x10resting_quantity\x18\x04 \x01(\x03R\x0frestingQuantity\"f\n" +
	"\x12CancelOrderRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\"8\n" +
	"\x13CancelOrderResponse\x12!\n" +
	"\flog_position\x18\x01 \x01(\x03R\vlogPosition\"-\n" +
	"\x13StreamTradesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\xf4\x02\n" +
	"\x05Trade\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\x03R\atradeId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12$\n" +
	"\x0emaker_order_id\x18\x05 \x01(\x03R\fmakerOrderId\x12$\n" +
	"\x0etaker_order_id\x18\x06 \x01(\x03R\ftakerOrderId\x12(\n" +
	"\x10maker_account_id\x18\a \x01(\tR\x0emakerAccountId\x12(\n" +
	"\x10taker_account_id\x18\b \x01(\tR\x0etakerAccountId\x121\n" +
	"\x15executed_at_unix_nano\x18\t \x01(\x03R\x12executedAtUnixNano\x123\n" +
	"\n" +
	"taker_side\x18\n" +
	" \x01(\x0e2\x14.dhukuti.oms.v1.SideR\ttakerSide*9\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSIDE_BUY\x10\x01\x12\r\n" +
	"\tSIDE_SELL\x10\x02*T\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x01\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x022\x89\x02\n" +
	"\fOrderService\x12S\n" +
	"\n" +
	"PlaceOrder\x12!.dhukuti.oms.v1.PlaceOrderRequest\x1a\".dhukuti.oms.v1.PlaceOrderResponse\x12V\n" +
	"\vCancelOrder\x12\".dhukuti.oms.v1.CancelOrderRequest\x1a#.dhukuti.oms.v1.CancelOrderResponse\x12L\n" +
	"\fStreamTrades\x12#.dhukuti.oms.v1.StreamTradesRequest\x1a\x15.dhukuti.oms.v1.Trade0\x01B'Z%github.com/Poudel0/OMS/internal/pb;pbb\x06proto3"

var (
	file_dhukuti_oms_v1_oms_proto_rawDescOnce sync.Once
	file_dhukuti_oms_v1_oms_proto_rawDescData []byte
)

func file_dhukuti_oms_v1_oms_proto_rawDescGZIP() []byte {
	file_dhukuti_oms_v1_oms_proto_rawDescOnce.Do(func() {
		file_dhukuti_oms_v1_oms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dhukuti_oms_v1_oms_proto_rawDesc), len(file_dhukuti_oms_v1_oms_proto_rawDesc)))
	})
	return file_dhukuti_oms_v1_oms_proto_rawDescData
}

var file_dhukuti_oms_v1_oms_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dhukuti_oms_v1_oms_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dhukuti_oms_v1_oms_proto_goTypes = []any{
	(Side)(0),                   // 0: dhukuti.oms.v1.Side
	(OrderType)(0),              // 1: dhukuti.oms.v1.OrderType
	(*PlaceOrderRequest)(nil),   // 2: dhukuti.oms.v1.PlaceOrderRequest
	(*PlaceOrderResponse)(nil),  // 3: dhukuti.oms.v1.PlaceOrderResponse
	(*CancelOrderRequest)(nil),  // 4: dhukuti.oms.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil), // 5: dhukuti.oms.v1.CancelOrderResponse
	(*StreamTradesRequest)(nil), // 6: dhukuti.oms.v1.StreamTradesRequest
	(*Trade)(nil),               // 7: dhukuti.oms.v1.Trade
}
var file_dhukuti_oms_v1_oms_proto_depIdxs = []int32{
	0, // 0: dhukuti.oms.v1.PlaceOrderRequest.side:type_name -> dhukuti.oms.v1.Side
	1, // 1: dhukuti.oms.v1.PlaceOrderRequest.type:type_name -> dhukuti.oms.v1.OrderType
	7, // 2: dhukuti.oms.v1.PlaceOrderResponse.trades:type_name -> dhukuti.oms.v1.Trade
	0, // 3: dhukuti.oms.v1.Trade.taker_side:type_name -> dhukuti.oms.v1.Side
	2, // 4: dhukuti.oms.v1.OrderService.PlaceOrder:input_type -> dhukuti.oms.v1.PlaceOrderRequest
	4, // 5: dhukuti.oms.v1.OrderService.CancelOrder:input_type -> dhukuti.oms.v1.CancelOrderRequest
	6, // 6: dhukuti.oms.v1.OrderService.StreamTrades:input_type -> dhukuti.oms.v1.StreamTradesRequest
	3, // 7: dhukuti.oms.v1.OrderService.PlaceOrder:output_type -> dhukuti.oms.v1.PlaceOrderResponse
	5, // 8: dhukuti.oms.v1.OrderService.CancelOrder:output_type -> dhukuti.oms.v1.CancelOrderResponse
	7, // 9: dhukuti.oms.v1.OrderService.StreamTrades:output_type -> dhukuti.oms.v1.Trade
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dhukuti_oms_v1_oms_proto_init() }
func file_dhukuti_oms_v1_oms_proto_init() {
	if File_dhukuti_oms_v1_oms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dhukuti_oms_v1_oms_proto_rawDesc), len(file_dhukuti_oms_v1_oms_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dhukuti_oms_v1_oms_proto_goTypes,
		DependencyIndexes: file_dhukuti_oms_v1_oms_proto_depIdxs,
		EnumInfos:         file_dhukuti_oms_v1_oms_proto_enumTypes,
		MessageInfos:      file_dhukuti_oms_v1_oms_proto_msgTypes,
	}.Build()
	File_dhukuti_oms_v1_oms_proto = out.File
	file_dhukuti_oms_v1_oms_proto_goTypes = nil
	file_dhukuti_oms_v1_oms_proto_depIdxs = nil
}
