// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: dhukuti/oms/v1/oms.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WALRecordKind mirrors the two mutations the log replays.
type WALRecordKind int32

const (
	WALRecordKind_WAL_RECORD_KIND_UNSPECIFIED WALRecordKind = 0
	WALRecordKind_WAL_RECORD_KIND_SUBMIT      WALRecordKind = 1
	WALRecordKind_WAL_RECORD_KIND_CANCEL      WALRecordKind = 2
)

// Enum value maps for WALRecordKind.
var (
	WALRecordKind_name = map[int32]string{
		0: "WAL_RECORD_KIND_UNSPECIFIED",
		1: "WAL_RECORD_KIND_SUBMIT",
		2: "WAL_RECORD_KIND_CANCEL",
	}
	WALRecordKind_value = map[string]int32{
		"WAL_RECORD_KIND_UNSPECIFIED": 0,
		"WAL_RECORD_KIND_SUBMIT":      1,
		"WAL_RECORD_KIND_CANCEL":      2,
	}
)

func (x WALRecordKind) Enum() *WALRecordKind {
	p := new(WALRecordKind)
	*p = x
	return p
}

func (x WALRecordKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WALRecordKind) Descriptor() protoreflect.EnumDescriptor {
	return file_dhukuti_oms_v1_oms_proto_enumTypes[0].Descriptor()
}

func (WALRecordKind) Type() protoreflect.EnumType {
	return &file_dhukuti_oms_v1_oms_proto_enumTypes[0]
}

func (x WALRecordKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WALRecordKind.Descriptor instead.
func (WALRecordKind) EnumDescriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{0}
}

// Side is the direction of an order. The unspecified zero value is invalid
// rather than defaulting, so a caller that forgets the field is rejected
// instead of silently having its order treated as a buy.
type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_BUY":         1,
		"SIDE_SELL":        2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_dhukuti_oms_v1_oms_proto_enumTypes[1].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_dhukuti_oms_v1_oms_proto_enumTypes[1]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{1}
}

// OrderType is LIMIT or MARKET. Unspecified is invalid, same reasoning as Side.
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
	OrderType_ORDER_TYPE_MARKET      OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_LIMIT",
		2: "ORDER_TYPE_MARKET",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_LIMIT":       1,
		"ORDER_TYPE_MARKET":      2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_dhukuti_oms_v1_oms_proto_enumTypes[2].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_dhukuti_oms_v1_oms_proto_enumTypes[2]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{2}
}

type GetBookSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookSnapshotRequest) Reset() {
	*x = GetBookSnapshotRequest{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookSnapshotRequest) ProtoMessage() {}

func (x *GetBookSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetBookSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{0}
}

func (x *GetBookSnapshotRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetBookSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// depth_json is L2 depth: total resting quantity per price, both sides, as
	// JSON. Aggregated rather than per-order, so it exposes no queue positions.
	DepthJson string `protobuf:"bytes,1,opt,name=depth_json,json=depthJson,proto3" json:"depth_json,omitempty"`
	// log_position is how far this node's log had advanced when the snapshot was
	// taken, which is what makes two nodes' snapshots comparable.
	LogPosition   int64 `protobuf:"varint,2,opt,name=log_position,json=logPosition,proto3" json:"log_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookSnapshotResponse) Reset() {
	*x = GetBookSnapshotResponse{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookSnapshotResponse) ProtoMessage() {}

func (x *GetBookSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetBookSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{1}
}

func (x *GetBookSnapshotResponse) GetDepthJson() string {
	if x != nil {
		return x.DepthJson
	}
	return ""
}

func (x *GetBookSnapshotResponse) GetLogPosition() int64 {
	if x != nil {
		return x.LogPosition
	}
	return 0
}

type ListSymbolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSymbolsRequest) Reset() {
	*x = ListSymbolsRequest{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSymbolsRequest) ProtoMessage() {}

func (x *ListSymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSymbolsRequest.ProtoReflect.Descriptor instead.
func (*ListSymbolsRequest) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{2}
}

type ListSymbolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSymbolsResponse) Reset() {
	*x = ListSymbolsResponse{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSymbolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSymbolsResponse) ProtoMessage() {}

func (x *ListSymbolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSymbolsResponse.ProtoReflect.Descriptor instead.
func (*ListSymbolsResponse) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{3}
}

func (x *ListSymbolsResponse) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type StreamWALRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Symbol string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// after_position streams records strictly above this log position. A follower
	// sends the highest position it has durably applied, so 0 means "from the
	// beginning" and there is no separate full-copy step -- the log IS the
	// snapshot.
	AfterPosition int64 `protobuf:"varint,2,opt,name=after_position,json=afterPosition,proto3" json:"after_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamWALRequest) Reset() {
	*x = StreamWALRequest{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamWALRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamWALRequest) ProtoMessage() {}

func (x *StreamWALRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamWALRequest.ProtoReflect.Descriptor instead.
func (*StreamWALRequest) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{4}
}

func (x *StreamWALRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StreamWALRequest) GetAfterPosition() int64 {
	if x != nil {
		return x.AfterPosition
	}
	return 0
}

type WALRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// position is the record's log position, assigned by the primary. The
	// follower stores records under the primary's positions, never its own:
	// renumbering would make the follower's log a different log and break resume.
	Position         int64         `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	LoggedAtUnixNano int64         `protobuf:"varint,2,opt,name=logged_at_unix_nano,json=loggedAtUnixNano,proto3" json:"logged_at_unix_nano,omitempty"`
	Kind             WALRecordKind `protobuf:"varint,3,opt,name=kind,proto3,enum=dhukuti.oms.v1.WALRecordKind" json:"kind,omitempty"`
	// Set when kind is SUBMIT.
	Order *Order `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	// Set when kind is CANCEL.
	CancelOrderId int64 `protobuf:"varint,5,opt,name=cancel_order_id,json=cancelOrderId,proto3" json:"cancel_order_id,omitempty"`
	// cancel_requested_by carries the ownership constraint the cancel was checked
	// against. It has to travel: the follower re-evaluates the constraint, so
	// omitting it would let a cancel that the primary refused succeed on the
	// follower, and the two books would diverge.
	CancelRequestedBy string `protobuf:"bytes,6,opt,name=cancel_requested_by,json=cancelRequestedBy,proto3" json:"cancel_requested_by,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WALRecord) Reset() {
	*x = WALRecord{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALRecord) ProtoMessage() {}

func (x *WALRecord) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALRecord.ProtoReflect.Descriptor instead.
func (*WALRecord) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{5}
}

func (x *WALRecord) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *WALRecord) GetLoggedAtUnixNano() int64 {
	if x != nil {
		return x.LoggedAtUnixNano
	}
	return 0
}

func (x *WALRecord) GetKind() WALRecordKind {
	if x != nil {
		return x.Kind
	}
	return WALRecordKind_WAL_RECORD_KIND_UNSPECIFIED
}

func (x *WALRecord) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *WALRecord) GetCancelOrderId() int64 {
	if x != nil {
		return x.CancelOrderId
	}
	return 0
}

func (x *WALRecord) GetCancelRequestedBy() string {
	if x != nil {
		return x.CancelRequestedBy
	}
	return ""
}

// Order is an order as the log recorded it, with the venue-assigned id already
// in place.
type Order struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderId          int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol           string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	AccountId        string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Type             OrderType              `protobuf:"varint,4,opt,name=type,proto3,enum=dhukuti.oms.v1.OrderType" json:"type,omitempty"`
	Price            int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity         int64                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Side             Side                   `protobuf:"varint,7,opt,name=side,proto3,enum=dhukuti.oms.v1.Side" json:"side,omitempty"`
	PlacedAtUnixNano int64                  `protobuf:"varint,8,opt,name=placed_at_unix_nano,json=placedAtUnixNano,proto3" json:"placed_at_unix_nano,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{6}
}

func (x *Order) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Order) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Order) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Order) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *Order) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *Order) GetPlacedAtUnixNano() int64 {
	if x != nil {
		return x.PlacedAtUnixNano
	}
	return 0
}

type WALBatch struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Records []*WALRecord           `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// primary_last_position is the highest position the primary had when it sent
	// this batch, so a follower can compute its own lag without a round trip.
	PrimaryLastPosition int64 `protobuf:"varint,2,opt,name=primary_last_position,json=primaryLastPosition,proto3" json:"primary_last_position,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WALBatch) Reset() {
	*x = WALBatch{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALBatch) ProtoMessage() {}

func (x *WALBatch) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALBatch.ProtoReflect.Descriptor instead.
func (*WALBatch) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{7}
}

func (x *WALBatch) GetRecords() []*WALRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *WALBatch) GetPrimaryLastPosition() int64 {
	if x != nil {
		return x.PrimaryLastPosition
	}
	return 0
}

type ReportProgressRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Symbol          string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	AppliedPosition int64                  `protobuf:"varint,2,opt,name=applied_position,json=appliedPosition,proto3" json:"applied_position,omitempty"`
	// applied_at is the logged_at of the record at applied_position, which is what
	// turns a lag in records into a lag in time.
	AppliedRecordLoggedAtUnixNano int64 `protobuf:"varint,3,opt,name=applied_record_logged_at_unix_nano,json=appliedRecordLoggedAtUnixNano,proto3" json:"applied_record_logged_at_unix_nano,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ReportProgressRequest) Reset() {
	*x = ReportProgressRequest{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProgressRequest) ProtoMessage() {}

func (x *ReportProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProgressRequest.ProtoReflect.Descriptor instead.
func (*ReportProgressRequest) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{8}
}

func (x *ReportProgressRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ReportProgressRequest) GetAppliedPosition() int64 {
	if x != nil {
		return x.AppliedPosition
	}
	return 0
}

func (x *ReportProgressRequest) GetAppliedRecordLoggedAtUnixNano() int64 {
	if x != nil {
		return x.AppliedRecordLoggedAtUnixNano
	}
	return 0
}

type ReportProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportProgressResponse) Reset() {
	*x = ReportProgressResponse{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProgressResponse) ProtoMessage() {}

func (x *ReportProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProgressResponse.ProtoReflect.Descriptor instead.
func (*ReportProgressResponse) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{9}
}

type ReplicationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationStatusRequest) Reset() {
	*x = ReplicationStatusRequest{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationStatusRequest) ProtoMessage() {}

func (x *ReplicationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationStatusRequest.ProtoReflect.Descriptor instead.
func (*ReplicationStatusRequest) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{10}
}

type SymbolLag struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Symbol           string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PrimaryPosition  int64                  `protobuf:"varint,2,opt,name=primary_position,json=primaryPosition,proto3" json:"primary_position,omitempty"`
	FollowerPosition int64                  `protobuf:"varint,3,opt,name=follower_position,json=followerPosition,proto3" json:"follower_position,omitempty"`
	// records_behind is primary_position - follower_position.
	RecordsBehind int64 `protobuf:"varint,4,opt,name=records_behind,json=recordsBehind,proto3" json:"records_behind,omitempty"`
	// millis_behind is now minus the logged_at of the follower's last applied
	// record. It is 0 when no follower has ever reported.
	MillisBehind  int64 `protobuf:"varint,5,opt,name=millis_behind,json=millisBehind,proto3" json:"millis_behind,omitempty"`
	FollowerSeen  bool  `protobuf:"varint,6,opt,name=follower_seen,json=followerSeen,proto3" json:"follower_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolLag) Reset() {
	*x = SymbolLag{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolLag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolLag) ProtoMessage() {}

func (x *SymbolLag) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolLag.ProtoReflect.Descriptor instead.
func (*SymbolLag) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{11}
}

func (x *SymbolLag) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SymbolLag) GetPrimaryPosition() int64 {
	if x != nil {
		return x.PrimaryPosition
	}
	return 0
}

func (x *SymbolLag) GetFollowerPosition() int64 {
	if x != nil {
		return x.FollowerPosition
	}
	return 0
}

func (x *SymbolLag) GetRecordsBehind() int64 {
	if x != nil {
		return x.RecordsBehind
	}
	return 0
}

func (x *SymbolLag) GetMillisBehind() int64 {
	if x != nil {
		return x.MillisBehind
	}
	return 0
}

func (x *SymbolLag) GetFollowerSeen() bool {
	if x != nil {
		return x.FollowerSeen
	}
	return false
}

type ReplicationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []*SymbolLag           `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationStatusResponse) Reset() {
	*x = ReplicationStatusResponse{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationStatusResponse) ProtoMessage() {}

func (x *ReplicationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationStatusResponse.ProtoReflect.Descriptor instead.
func (*ReplicationStatusResponse) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{12}
}

func (x *ReplicationStatusResponse) GetSymbols() []*SymbolLag {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type PlaceOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// symbol is the instrument, e.g. "NABIL". Uppercase A-Z0-9, max 12 chars.
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// account_id is the account the order is placed for. Authenticating that
	// the caller is entitled to act for this account is out of scope for v1
	// (see ADR-005) — the field is trusted as sent.
	AccountId string    `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Side      Side      `protobuf:"varint,3,opt,name=side,proto3,enum=dhukuti.oms.v1.Side" json:"side,omitempty"`
	Type      OrderType `protobuf:"varint,4,opt,name=type,proto3,enum=dhukuti.oms.v1.OrderType" json:"type,omitempty"`
	// price is in ticks and is ignored for MARKET orders.
	Price         int64 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64 `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{13}
}

func (x *PlaceOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PlaceOrderRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *PlaceOrderRequest) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PlaceOrderRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type PlaceOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order_id is assigned by the venue, not the client. A client-supplied ID
	// would let one client claim another's identifier and then cancel its
	// orders.
	OrderId int64 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// log_position is the order's write-ahead log position, durable before any
	// matching happened. It is not an order ID — cancels get positions too.
	LogPosition int64 `protobuf:"varint,2,opt,name=log_position,json=logPosition,proto3" json:"log_position,omitempty"`
	// trades is every execution this order caused, in match order. Empty means
	// the order rested without crossing anything.
	Trades []*Trade `protobuf:"bytes,3,rep,name=trades,proto3" json:"trades,omitempty"`
	// resting_quantity is what remains in the book. A MARKET order's unfilled
	// remainder is dropped rather than rested, so this is always 0 for MARKET.
	RestingQuantity int64 `protobuf:"varint,4,opt,name=resting_quantity,json=restingQuantity,proto3" json:"resting_quantity,omitempty"`
	// self_prevented_order_ids lists your own resting orders that were cancelled
	// because this order would otherwise have traded with your own account. The
	// venue cancels the resting side rather than printing a wash trade, and says
	// so here — an order silently vanishing from the book would be worse.
	SelfPreventedOrderIds []int64 `protobuf:"varint,5,rep,packed,name=self_prevented_order_ids,json=selfPreventedOrderIds,proto3" json:"self_prevented_order_ids,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{14}
}

func (x *PlaceOrderResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PlaceOrderResponse) GetLogPosition() int64 {
	if x != nil {
		return x.LogPosition
	}
	return 0
}

func (x *PlaceOrderResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

func (x *PlaceOrderResponse) GetRestingQuantity() int64 {
	if x != nil {
		return x.RestingQuantity
	}
	return 0
}

func (x *PlaceOrderResponse) GetSelfPreventedOrderIds() []int64 {
	if x != nil {
		return x.SelfPreventedOrderIds
	}
	return nil
}

type CancelOrderRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Symbol  string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// account_id must match the account that placed the order. Same v1 caveat
	// as PlaceOrderRequest.account_id: the claim is checked but not
	// authenticated.
	AccountId     string `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{15}
}

func (x *CancelOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CancelOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CancelOrderRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogPosition   int64                  `protobuf:"varint,1,opt,name=log_position,json=logPosition,proto3" json:"log_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{16}
}

func (x *CancelOrderResponse) GetLogPosition() int64 {
	if x != nil {
		return x.LogPosition
	}
	return 0
}

type StreamTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTradesRequest) Reset() {
	*x = StreamTradesRequest{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTradesRequest) ProtoMessage() {}

func (x *StreamTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTradesRequest.ProtoReflect.Descriptor instead.
func (*StreamTradesRequest) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{17}
}

func (x *StreamTradesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type Trade struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// trade_id is unique within a symbol.
	TradeId int64  `protobuf:"varint,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	Symbol  string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// price is always the resting (maker) order's price, never the incoming
	// taker's — the taker crossed a price that was already on offer.
	Price          int64  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity       int64  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	MakerOrderId   int64  `protobuf:"varint,5,opt,name=maker_order_id,json=makerOrderId,proto3" json:"maker_order_id,omitempty"`
	TakerOrderId   int64  `protobuf:"varint,6,opt,name=taker_order_id,json=takerOrderId,proto3" json:"taker_order_id,omitempty"`
	MakerAccountId string `protobuf:"bytes,7,opt,name=maker_account_id,json=makerAccountId,proto3" json:"maker_account_id,omitempty"`
	TakerAccountId string `protobuf:"bytes,8,opt,name=taker_account_id,json=takerAccountId,proto3" json:"taker_account_id,omitempty"`
	// executed_at is a metric, not an ordering key. Matching order is
	// determined by log position, and replay does not reproduce this field —
	// see ADR-003.
	ExecutedAtUnixNano int64 `protobuf:"varint,9,opt,name=executed_at_unix_nano,json=executedAtUnixNano,proto3" json:"executed_at_unix_nano,omitempty"`
	// taker_side is the incoming order's direction, which is what says who
	// bought: on SIDE_BUY the taker pays cash and receives shares. Without it a
	// trade names both parties but not which way value moved.
	TakerSide     Side `protobuf:"varint,10,opt,name=taker_side,json=takerSide,proto3,enum=dhukuti.oms.v1.Side" json:"taker_side,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_dhukuti_oms_v1_oms_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_dhukuti_oms_v1_oms_proto_rawDescGZIP(), []int{18}
}

func (x *Trade) GetTradeId() int64 {
	if x != nil {
		return x.TradeId
	}
	return 0
}

func (x *Trade) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Trade) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetMakerOrderId() int64 {
	if x != nil {
		return x.MakerOrderId
	}
	return 0
}

func (x *Trade) GetTakerOrderId() int64 {
	if x != nil {
		return x.TakerOrderId
	}
	return 0
}

func (x *Trade) GetMakerAccountId() string {
	if x != nil {
		return x.MakerAccountId
	}
	return ""
}

func (x *Trade) GetTakerAccountId() string {
	if x != nil {
		return x.TakerAccountId
	}
	return ""
}

func (x *Trade) GetExecutedAtUnixNano() int64 {
	if x != nil {
		return x.ExecutedAtUnixNano
	}
	return 0
}

func (x *Trade) GetTakerSide() Side {
	if x != nil {
		return x.TakerSide
	}
	return Side_SIDE_UNSPECIFIED
}

var File_dhukuti_oms_v1_oms_proto protoreflect.FileDescriptor

const file_dhukuti_oms_v1_oms_proto_rawDesc = "" +
	"\n" +
	"\x18dhukuti/oms/v1/oms.proto\x12\x0edhukuti.oms.v1\"0\n" +
	"\x16GetBookSnapshotRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"[\n" +
	"\x17GetBookSnapshotResponse\x12\x1d\n" +
	"\n" +
	"depth_json\x18\x01 \x01(\tR\tdepthJson\x12!\n" +
	"\flog_position\x18\x02 \x01(\x03R\vlogPosition\"\x14\n" +
	"\x12ListSymbolsRequest\"/\n" +
	"\x13ListSymbolsResponse\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"Q\n" +
	"\x10StreamWALRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12%\n" +
	"\x0eafter_position\x18\x02 \x01(\x03R\rafterPosition\"\x8e\x02\n" +
	"\tWALRecord\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x03R\bposition\x12-\n" +
	"\x13logged_at_unix_nano\x18\x02 \x01(\x03R\x10loggedAtUnixNano\x121\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1d.dhukuti.oms.v1.WALRecordKindR\x04kind\x12+\n" +
	"\x05order\x18\x04 \x01(\v2\x15.dhukuti.oms.v1.OrderR\x05order\x12&\n" +
	"\x0fcancel_order_id\x18\x05 \x01(\x03R\rcancelOrderId\x12.\n" +
	"\x13cancel_requested_by\x18\x06 \x01(\tR\x11cancelRequestedBy\"\x93\x02\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12-\n" +
	"\x04type\x18\x04 \x01(\x0e2\x19.dhukuti.oms.v1.OrderTypeR\x04type\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x03R\bquantity\x12(\n" +
	"\x04side\x18\a \x01(\x0e2\x14.dhukuti.oms.v1.SideR\x04side\x12-\n" +
	"\x13placed_at_unix_nano\x18\b \x01(\x03R\x10placedAtUnixNano\"s\n" +
	"\bWALBatch\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.dhukuti.oms.v1.WALRecordR\arecords\x122\n" +
	"\x15primary_last_position\x18\x02 \x01(\x03R\x13primaryLastPosition\"\xa5\x01\n" +
	"\x15ReportProgressRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12)\n" +
	"\x10applied_position\x18\x02 \x01(\x03R\x0fappliedPosition\x12I\n" +
	"\"applied_record_logged_at_unix_nano\x18\x03 \x01(\x03R\x1dappliedRecordLoggedAtUnixNano\"\x18\n" +
	"\x16ReportProgressResponse\"\x1a\n" +
	"\x18ReplicationStatusRequest\"\xec\x01\n" +
	"\tSymbolLag\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12)\n" +
	"\x10primary_position\x18\x02 \x01(\x03R\x0fprimaryPosition\x12+\n" +
	"\x11follower_position\x18\x03 \x01(\x03R\x10followerPosition\x12%\n" +
	"\x0erecords_behind\x18\x04 \x01(\x03R\rrecordsBehind\x12#\n" +
	"\rmillis_behind\x18\x05 \x01(\x03R\fmillisBehind\x12#\n" +
	"\rfollower_seen\x18\x06 \x01(\bR\ffollowerSeen\"P\n" +
	"\x19ReplicationStatusResponse\x123\n" +
	"\asymbols\x18\x01 \x03(\v2\x19.dhukuti.oms.v1.SymbolLagR\asymbols\"\xd5\x01\n" +
	"\x11PlaceOrderRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12(\n" +
	"\x04side\x18\x03 \x01(\x0e2\x14.dhukuti.oms.v1.SideR\x04side\x12-\n" +
	"\x04type\x18\x04 \x01(\x0e2\x19.dhukuti.oms.v1.OrderTypeR\x04type\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x03R\bquantity\"\xe5\x01\n" +
	"\x12PlaceOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12!\n" +
	"\flog_position\x18\x02 \x01(\x03R\vlogPosition\x12-\n" +
	"\x06trades\x18\x03 \x03(\v2\x15.dhukuti.oms.v1.TradeR\x06trades\x12)\n" +
	"\x10resting_quantity\x18\x04 \x01(\x03R\x0frestingQuantity\x127\n" +
	"\x18self_prevented_order_ids\x18\x05 \x03(\x03R\x15selfPreventedOrderIds\"f\n" +
	"\x12CancelOrderRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\"8\n" +
	"\x13CancelOrderResponse\x12!\n" +
	"\flog_position\x18\x01 \x01(\x03R\vlogPosition\"-\n" +
	"\x13StreamTradesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\xf4\x02\n" +
	"\x05Trade\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\x03R\atradeId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12$\n" +
	"\x0emaker_order_id\x18\x05 \x01(\x03R\fmakerOrderId\x12$\n" +
	"\x0etaker_order_id\x18\x06 \x01(\x03R\ftakerOrderId\x12(\n" +
	"\x10maker_account_id\x18\a \x01(\tR\x0emakerAccountId\x12(\n" +
	"\x10taker_account_id\x18\b \x01(\tR\x0etakerAccountId\x121\n" +
	"\x15executed_at_unix_nano\x18\t \x01(\x03R\x12executedAtUnixNano\x123\n" +
	"\n" +
	"taker_side\x18\n" +
	" \x01(\x0e2\x14.dhukuti.oms.v1.SideR\ttakerSide*h\n" +
	"\rWALRecordKind\x12\x1f\n" +
	"\x1bWAL_RECORD_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WAL_RECORD_KIND_SUBMIT\x10\x01\x12\x1a\n" +
	"\x16WAL_RECORD_KIND_CANCEL\x10\x02*9\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSIDE_BUY\x10\x01\x12\r\n" +
	"\tSIDE_SELL\x10\x02*T\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x01\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x022\xed\x02\n" +
	"\fOrderService\x12S\n" +
	"\n" +
	"PlaceOrder\x12!.dhukuti.oms.v1.PlaceOrderRequest\x1a\".dhukuti.oms.v1.PlaceOrderResponse\x12V\n" +
	"\vCancelOrder\x12\".dhukuti.oms.v1.CancelOrderRequest\x1a#.dhukuti.oms.v1.CancelOrderResponse\x12L\n" +
	"\fStreamTrades\x12#.dhukuti.oms.v1.StreamTradesRequest\x1a\x15.dhukuti.oms.v1.Trade0\x01\x12b\n" +
	"\x0fGetBookSnapshot\x12&.dhukuti.oms.v1.GetBookSnapshotRequest\x1a'.dhukuti.oms.v1.GetBookSnapshotResponse2\x82\x03\n" +
	"\x12ReplicationService\x12V\n" +
	"\vListSymbols\x12\".dhukuti.oms.v1.ListSymbolsRequest\x1a#.dhukuti.oms.v1.ListSymbolsResponse\x12I\n" +
	"\tStreamWAL\x12 .dhukuti.oms.v1.StreamWALRequest\x1a\x18.dhukuti.oms.v1.WALBatch0\x01\x12_\n" +
	"\x0eReportProgress\x12%.dhukuti.oms.v1.ReportProgressRequest\x1a&.dhukuti.oms.v1.ReportProgressResponse\x12h\n" +
	"\x11ReplicationStatus\x12(.dhukuti.oms.v1.ReplicationStatusRequest\x1a).dhukuti.oms.v1.ReplicationStatusResponseB'Z%github.com/Poudel0/OMS/internal/pb;pbb\x06proto3"

var (
	file_dhukuti_oms_v1_oms_proto_rawDescOnce sync.Once
	file_dhukuti_oms_v1_oms_proto_rawDescData []byte
)

func file_dhukuti_oms_v1_oms_proto_rawDescGZIP() []byte {
	file_dhukuti_oms_v1_oms_proto_rawDescOnce.Do(func() {
		file_dhukuti_oms_v1_oms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dhukuti_oms_v1_oms_proto_rawDesc), len(file_dhukuti_oms_v1_oms_proto_rawDesc)))
	})
	return file_dhukuti_oms_v1_oms_proto_rawDescData
}

var file_dhukuti_oms_v1_oms_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_dhukuti_oms_v1_oms_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_dhukuti_oms_v1_oms_proto_goTypes = []any{
	(WALRecordKind)(0),                // 0: dhukuti.oms.v1.WALRecordKind
	(Side)(0),                         // 1: dhukuti.oms.v1.Side
	(OrderType)(0),                    // 2: dhukuti.oms.v1.OrderType
	(*GetBookSnapshotRequest)(nil),    // 3: dhukuti.oms.v1.GetBookSnapshotRequest
	(*GetBookSnapshotResponse)(nil),   // 4: dhukuti.oms.v1.GetBookSnapshotResponse
	(*ListSymbolsRequest)(nil),        // 5: dhukuti.oms.v1.ListSymbolsRequest
	(*ListSymbolsResponse)(nil),       // 6: dhukuti.oms.v1.ListSymbolsResponse
	(*StreamWALRequest)(nil),          // 7: dhukuti.oms.v1.StreamWALRequest
	(*WALRecord)(nil),                 // 8: dhukuti.oms.v1.WALRecord
	(*Order)(nil),                     // 9: dhukuti.oms.v1.Order
	(*WALBatch)(nil),                  // 10: dhukuti.oms.v1.WALBatch
	(*ReportProgressRequest)(nil),     // 11: dhukuti.oms.v1.ReportProgressRequest
	(*ReportProgressResponse)(nil),    // 12: dhukuti.oms.v1.ReportProgressResponse
	(*ReplicationStatusRequest)(nil),  // 13: dhukuti.oms.v1.ReplicationStatusRequest
	(*SymbolLag)(nil),                 // 14: dhukuti.oms.v1.SymbolLag
	(*ReplicationStatusResponse)(nil), // 15: dhukuti.oms.v1.ReplicationStatusResponse
	(*PlaceOrderRequest)(nil),         // 16: dhukuti.oms.v1.PlaceOrderRequest
	(*PlaceOrderResponse)(nil),        // 17: dhukuti.oms.v1.PlaceOrderResponse
	(*CancelOrderRequest)(nil),        // 18: dhukuti.oms.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),       // 19: dhukuti.oms.v1.CancelOrderResponse
	(*StreamTradesRequest)(nil),       // 20: dhukuti.oms.v1.StreamTradesRequest
	(*Trade)(nil),                     // 21: dhukuti.oms.v1.Trade
}
var file_dhukuti_oms_v1_oms_proto_depIdxs = []int32{
	0,  // 0: dhukuti.oms.v1.WALRecord.kind:type_name -> dhukuti.oms.v1.WALRecordKind
	9,  // 1: dhukuti.oms.v1.WALRecord.order:type_name -> dhukuti.oms.v1.Order
	2,  // 2: dhukuti.oms.v1.Order.type:type_name -> dhukuti.oms.v1.OrderType
	1,  // 3: dhukuti.oms.v1.Order.side:type_name -> dhukuti.oms.v1.Side
	8,  // 4: dhukuti.oms.v1.WALBatch.records:type_name -> dhukuti.oms.v1.WALRecord
	14, // 5: dhukuti.oms.v1.ReplicationStatusResponse.symbols:type_name -> dhukuti.oms.v1.SymbolLag
	1,  // 6: dhukuti.oms.v1.PlaceOrderRequest.side:type_name -> dhukuti.oms.v1.Side
	2,  // 7: dhukuti.oms.v1.PlaceOrderRequest.type:type_name -> dhukuti.oms.v1.OrderType
	21, // 8: dhukuti.oms.v1.PlaceOrderResponse.trades:type_name -> dhukuti.oms.v1.Trade
	1,  // 9: dhukuti.oms.v1.Trade.taker_side:type_name -> dhukuti.oms.v1.Side
	16, // 10: dhukuti.oms.v1.OrderService.PlaceOrder:input_type -> dhukuti.oms.v1.PlaceOrderRequest
	18, // 11: dhukuti.oms.v1.OrderService.CancelOrder:input_type -> dhukuti.oms.v1.CancelOrderRequest
	20, // 12: dhukuti.oms.v1.OrderService.StreamTrades:input_type -> dhukuti.oms.v1.StreamTradesRequest
	3,  // 13: dhukuti.oms.v1.OrderService.GetBookSnapshot:input_type -> dhukuti.oms.v1.GetBookSnapshotRequest
	5,  // 14: dhukuti.oms.v1.ReplicationService.ListSymbols:input_type -> dhukuti.oms.v1.ListSymbolsRequest
	7,  // 15: dhukuti.oms.v1.ReplicationService.StreamWAL:input_type -> dhukuti.oms.v1.StreamWALRequest
	11, // 16: dhukuti.oms.v1.ReplicationService.ReportProgress:input_type -> dhukuti.oms.v1.ReportProgressRequest
	13, // 17: dhukuti.oms.v1.ReplicationService.ReplicationStatus:input_type -> dhukuti.oms.v1.ReplicationStatusRequest
	17, // 18: dhukuti.oms.v1.OrderService.PlaceOrder:output_type -> dhukuti.oms.v1.PlaceOrderResponse
	19, // 19: dhukuti.oms.v1.OrderService.CancelOrder:output_type -> dhukuti.oms.v1.CancelOrderResponse
	21, // 20: dhukuti.oms.v1.OrderService.StreamTrades:output_type -> dhukuti.oms.v1.Trade
	4,  // 21: dhukuti.oms.v1.OrderService.GetBookSnapshot:output_type -> dhukuti.oms.v1.GetBookSnapshotResponse
	6,  // 22: dhukuti.oms.v1.ReplicationService.ListSymbols:output_type -> dhukuti.oms.v1.ListSymbolsResponse
	10, // 23: dhukuti.oms.v1.ReplicationService.StreamWAL:output_type -> dhukuti.oms.v1.WALBatch
	12, // 24: dhukuti.oms.v1.ReplicationService.ReportProgress:output_type -> dhukuti.oms.v1.ReportProgressResponse
	15, // 25: dhukuti.oms.v1.ReplicationService.ReplicationStatus:output_type -> dhukuti.oms.v1.ReplicationStatusResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_dhukuti_oms_v1_oms_proto_init() }
func file_dhukuti_oms_v1_oms_proto_init() {
	if File_dhukuti_oms_v1_oms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dhukuti_oms_v1_oms_proto_rawDesc), len(file_dhukuti_oms_v1_oms_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_dhukuti_oms_v1_oms_proto_goTypes,
		DependencyIndexes: file_dhukuti_oms_v1_oms_proto_depIdxs,
		EnumInfos:         file_dhukuti_oms_v1_oms_proto_enumTypes,
		MessageInfos:      file_dhukuti_oms_v1_oms_proto_msgTypes,
	}.Build()
	File_dhukuti_oms_v1_oms_proto = out.File
	file_dhukuti_oms_v1_oms_proto_goTypes = nil
	file_dhukuti_oms_v1_oms_proto_depIdxs = nil
}
